name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Generate environment.ts
        run: |
          mkdir -p src/app/environment
          echo "export const environment = {
            production: true,
            cognito: {
              userPoolId: '${{ secrets.COGNITO_USER_POOL_ID }}',
              clientId: '${{ secrets.COGNITO_CLIENT_ID }}',
              domain: '${{ secrets.COGNITO_DOMAIN }}'
            },
            bgm: {
              url: 'https://api.bgm.tv/v0',
              authToken: '$BGM_AUTH_TOKEN',
              userAgent: 'dreaife/my-angular-project-test'
            }
          };" > src/app/environment/environment.ts

          ls src/app/environment

      - name: Build project
        run: npm run build -- --configuration production --base-href "/my-angular-project-test/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/my-angular-project/browser
          token: ${{ secrets.TOKEN }}

env:
  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
  BGM_AUTH_TOKEN: ${{ secrets.BGM_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  