name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 或者你要监控的分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 请根据项目需求修改 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Generate environment.prod.ts
        run: |
          # 创建 src/app/environment 目录（如果不存在）
          mkdir -p src/app/environment
          
          # 生成 environment.prod.ts 文件
          echo "export const environment = {
            production: true,
            cognito: {
              userPoolId: '$COGNITO_USER_POOL_ID',
              clientId: '$COGNITO_CLIENT_ID',
              domain: '$COGNITO_DOMAIN'
            },
            bgm: {
              url: 'https://api.bgm.tv/v0',
              authToken: '$BGM_AUTH_TOKEN',
              userAgent: 'dreaife/my-angular-project-test'
            }
          };" > src/app/environment/environment.prod.ts

          ls src/app/environment

      - name: Build project
        run: npm run build -- --configuration production --base-href "/my-angular-project-test/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/my-angular-project/browser  # 请根据实际输出路径填写
          token: ${{ secrets.TOKEN }}

env:
  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
  BGM_AUTH_TOKEN: ${{ secrets.BGM_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  